### ISSUE TITLE
ゲームGUIブランチのバグについて

### ISSUE THREAD

**Issue by rentour** [piroping/CHaserServer-HakodateBeta-#4]
GUIブランチのコードをダウンロードしCHaserSeverGUI.pyを実行したところ、待機開始を押しても、待機中に変わらないバグを発見しました。改善をお願いします。

**Comment by Pironium-dev** [comment]
デバッグのため、内部のデータフローをすべて見直します。

時間がものすごくかかってしまうのでご容赦を、、、

**Comment by Pironium-dev** [comment]
内部ロジックの修正完了しました。

動作確認できれば、ご一報お願いします。
